import { useState, useEffect } from "react";
import axios from "axios";

const useFetch = (endpoint, query) => {
  const [data, setData] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const options = {
    method: "GET",
    url: `https://jsearch.p.rapidapi.com/${endpoint}`,
    headers: {
      "X-RapidAPI-Key": "cb58eb5930msh6e9ab119efc5a4bp165371jsn1ad70c6b8f38",
      "X-RapidAPI-Host": "jsearch.p.rapidapi.com",
    },
    params: { ...query },
  };

  const fetchData = async () => {
    setIsLoading(true);

    try {
      // const response = await axios.request(options);
      // setData(response.data.data);
      if (endpoint == "search") {
        setData([
          {
            employer_name: "Mindpal",
            employer_logo:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKdbXDdBF2_8ZRV4qszl-0nJx1pneJLHoI9D9d&s=0",
            employer_website: null,
            employer_company_type: null,
            job_publisher: "LinkedIn",
            job_id: "EV02pCkgcY4AAAAAAAAAAA==",
            job_employment_type: "FULLTIME",
            job_title: "React Developer",
            job_apply_link:
              "https://www.linkedin.com/jobs/view/react-developer-at-mindpal-3656112725",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6065,
            job_description:
              "• We are looking for React Developers with experience ranging from junior to senior level.\n• Job Description\n• Creating and developing web applications using React and other front-end tools\n• Working with designers to translate graphical designs into visually appealing and intuitive user interfaces\n• Ensuring application performance and scalability through code optimization and problem-solving related to performance\n• Collaborating with the back-end team to integrate the front-end application with systems and databases\n• Testing and debugging applications to ensure reliability\n• Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications\n• Collaborating with the project team and management to understand business requirements and adjust work to company goals\n• Requirements\n• Minimum 2 years of experience working with React\n• Very good programming skills in JavaScript and TypeScript\n• Knowledge of software architecture, design patterns, and software development according to best practices\n• Communicative knowledge of English language\n• Additional advantage will be knowledge of other technologies\n• We Offer\n• B2B contract type\n• Full-time employment\n• Remote and flexible working hours\n\nRequirements\n\nResponsibilities",
            job_is_remote: false,
            job_posted_at_timestamp: 1688564550,
            job_posted_at_datetime_utc: "2023-07-05T13:42:30.000Z",
            job_city: "Wichita",
            job_state: "KS",
            job_country: "US",
            job_latitude: 37.687176,
            job_longitude: -97.330055,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=EV02pCkgcY4AAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: "2023-08-04T13:42:30.000Z",
            job_offer_expiration_timestamp: 1691156550,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: null,
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: true,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "Minimum 2 years of experience working with React",
                "Very good programming skills in JavaScript and TypeScript",
                "Knowledge of software architecture, design patterns, and software development according to best practices",
                "Communicative knowledge of English language",
              ],
              Responsibilities: [
                "Creating and developing web applications using React and other front-end tools",
                "Working with designers to translate graphical designs into visually appealing and intuitive user interfaces",
                "Ensuring application performance and scalability through code optimization and problem-solving related to performance",
                "Collaborating with the back-end team to integrate the front-end application with systems and databases",
                "Testing and debugging applications to ensure reliability",
                "Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications",
                "Collaborating with the project team and management to understand business requirements and adjust work to company goals",
              ],
              Benefits: ["Remote and flexible working hours"],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
          },
          {
            employer_name: "Mindpal",
            employer_logo:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKdbXDdBF2_8ZRV4qszl-0nJx1pneJLHoI9D9d&s=0",
            employer_website: null,
            employer_company_type: null,
            job_publisher: "LinkedIn",
            job_id: "Lw0rorqYNZ0AAAAAAAAAAA==",
            job_employment_type: "FULLTIME",
            job_title: "React Native Developer",
            job_apply_link:
              "https://www.linkedin.com/jobs/view/react-native-developer-at-mindpal-3657326287",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6065,
            job_description:
              "We are looking for React Native Developer\n\nResponsibilities\n• Develop and maintain high-quality mobile applications using React Native\n• Collaborate with cross-functional teams to define, design, and implement new features\n• Participate in code reviews to ensure code quality and adherence to best practices\n• Troubleshoot and debug software defects and issues\n• Optimize application performance for a smooth user experience\n• Stay updated with the latest industry trends and emerging technologies in mobile development\n\nRequirements\n• Minimum of 2 years of professional experience as a React Native Developer\n• Strong proficiency in React Native framework\n• Solid understanding of JavaScript, HTML, and CSS\n• Experience with mobile app development and the React Native ecosystem\n• Familiarity with RESTful APIs and integration of third-party libraries\n• Knowledge of version control systems (e.g., Git)\n• Strong problem-solving and debugging skills\n• Ability to work independently and collaboratively in a team environment\n• Excellent communication and interpersonal skills\n\nWe Offer\n• B2B contract type\n• Full-time job\n• Remote and flexible working hours\n\nRequirements\n\nResponsibilities",
            job_is_remote: false,
            job_posted_at_timestamp: 1688672569,
            job_posted_at_datetime_utc: "2023-07-06T19:42:49.000Z",
            job_city: "Fayetteville",
            job_state: "AR",
            job_country: "US",
            job_latitude: 36.062656,
            job_longitude: -94.16058,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=Lw0rorqYNZ0AAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: "2023-08-05T19:42:49.000Z",
            job_offer_expiration_timestamp: 1691264569,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: 24,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: null,
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: true,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "Minimum of 2 years of professional experience as a React Native Developer",
                "Strong proficiency in React Native framework",
                "Solid understanding of JavaScript, HTML, and CSS",
                "Experience with mobile app development and the React Native ecosystem",
                "Familiarity with RESTful APIs and integration of third-party libraries",
                "Knowledge of version control systems (e.g., Git)",
                "Strong problem-solving and debugging skills",
                "Ability to work independently and collaboratively in a team environment",
                "Excellent communication and interpersonal skills",
              ],
              Responsibilities: [
                "Develop and maintain high-quality mobile applications using React Native",
                "Collaborate with cross-functional teams to define, design, and implement new features",
                "Participate in code reviews to ensure code quality and adherence to best practices",
                "Troubleshoot and debug software defects and issues",
                "Optimize application performance for a smooth user experience",
                "Stay updated with the latest industry trends and emerging technologies in mobile development",
              ],
              Benefits: [
                "B2B contract type",
                "Full-time job",
                "Remote and flexible working hours",
              ],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113200",
            job_onet_job_zone: "4",
          },
          {
            employer_name: "Upwork",
            employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
            employer_website: "http://www.elance.com",
            employer_company_type: "Computer Services",
            job_publisher: "Upwork",
            job_id: "_chYZr9AO6QAAAAAAAAAAA==",
            job_employment_type: "CONTRACTOR",
            job_title: "React Developer needed for Website",
            job_apply_link:
              "https://www.upwork.com/freelance-jobs/apply/React-Developer-needed-for-Website_~01629262bb725e999a/",
            job_apply_is_direct: true,
            job_apply_quality_score: 0.681,
            job_description:
              "Dear freelancers!\n\nI'm a primary school teacher and my class has 30 students.\n\nI want a web developer who has rich experience in developing school websites.\n\nThis website contains three main pages - Welcome page, management page and score board.\n\n1. Welcome page\n\nThis page contains login, register pages.\n\n2. Management page\n\nThere are 3 main types of users - headmaster, vice headmaster and teacher.\n\nHeadmaster manages all teachers and students and vice headmaster manages scores of students.\n\nEach teacher managees their own classmembers.\n\n3. Score board\n\nA teacher can add and delete scores of his students and report average score to headmaster and vice headmaster.\n\nScoreboard is the main point of this project.\n\nAny web framework is available for this and I prefer MERN stack!\n\nI look forward to hearing you - freelancers.",
            job_is_remote: true,
            job_posted_at_timestamp: 1688661210,
            job_posted_at_datetime_utc: "2023-07-06T16:33:30.000Z",
            job_city: null,
            job_state: null,
            job_country: "US",
            job_latitude: 37.09024,
            job_longitude: -95.71289,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=_chYZr9AO6QAAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: [
              "MongoDB",
              "React",
              "JavaScript",
              "Web Development",
              "HTML",
              "HTML5",
              "CSS",
              "Web Design",
              "Node.js",
              "CSS 3",
            ],
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "I want a web developer who has rich experience in developing school websites",
              ],
              Responsibilities: [
                "Headmaster manages all teachers and students and vice headmaster manages scores of students",
              ],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
            job_naics_code: "541511",
            job_naics_name: "Custom Computer Programming Services",
          },
          {
            employer_name: "Mindpal",
            employer_logo:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKdbXDdBF2_8ZRV4qszl-0nJx1pneJLHoI9D9d&s=0",
            employer_website: null,
            employer_company_type: null,
            job_publisher: "LinkedIn",
            job_id: "zVjTmsomfrcAAAAAAAAAAA==",
            job_employment_type: "FULLTIME",
            job_title: "Fullstack Developer (Node.JS & React)",
            job_apply_link:
              "https://www.linkedin.com/jobs/view/fullstack-developer-node-js-react-at-mindpal-3656112689",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6065,
            job_description:
              "???? We are seeking a skilled Node.js and React Developer ????\n\nIf you are passionate about web development and have a solid understanding of both Node.js and React, we'd love to know you better!\n• Responsibilities:\n• Develop and maintain efficient and scalable web applications using Node.js and React\n• Collaborate with cross-functional teams to define, design, and ship new features\n• Troubleshoot and resolve software defects and issues\n• Optimize application performance for maximum speed and scalability\n• Stay updated with industry trends and emerging technologies\n• Requirements:\n• At least 2 years of professional experience as a Node.js and React Developer\n• Strong proficiency in Node.js and React frameworks\n• Solid understanding of JavaScript, HTML, and CSS\n• Experience with RESTful APIs and third-party libraries\n• Familiarity with version control systems (e.g., Git)\n• Strong problem-solving and debugging skills\n• Ability to work independently and collaboratively in a team environment\n• Excellent communication and interpersonal skills\n• We offer:\n• B2B contract type\n• Full-time job\n• Remote and flexible working hours\n\nRequirements\n\nResponsibilities",
            job_is_remote: false,
            job_posted_at_timestamp: 1688564525,
            job_posted_at_datetime_utc: "2023-07-05T13:42:05.000Z",
            job_city: "Fort Smith",
            job_state: "AR",
            job_country: "US",
            job_latitude: 35.384373,
            job_longitude: -94.42097,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=zVjTmsomfrcAAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: "2023-08-04T13:42:05.000Z",
            job_offer_expiration_timestamp: 1691156525,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: 24,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: null,
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: true,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "At least 2 years of professional experience as a Node.js and React Developer",
                "Strong proficiency in Node.js and React frameworks",
                "Solid understanding of JavaScript, HTML, and CSS",
                "Experience with RESTful APIs and third-party libraries",
                "Familiarity with version control systems (e.g., Git)",
                "Strong problem-solving and debugging skills",
                "Ability to work independently and collaboratively in a team environment",
                "Excellent communication and interpersonal skills",
              ],
              Responsibilities: [
                "Develop and maintain efficient and scalable web applications using Node.js and React",
                "Collaborate with cross-functional teams to define, design, and ship new features",
                "Troubleshoot and resolve software defects and issues",
                "Optimize application performance for maximum speed and scalability",
                "Stay updated with industry trends and emerging technologies",
              ],
              Benefits: ["Full-time job", "Remote and flexible working hours"],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
          },
          {
            employer_name: "Upwork",
            employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
            employer_website: "http://www.elance.com",
            employer_company_type: "Computer Services",
            job_publisher: "Upwork",
            job_id: "czqqS8z6oJ8AAAAAAAAAAA==",
            job_employment_type: "CONTRACTOR",
            job_title: "React developer needed",
            job_apply_link:
              "https://www.upwork.com/freelance-jobs/apply/React-developer-needed_~0175677e12f0336148/",
            job_apply_is_direct: true,
            job_apply_quality_score: 0.681,
            job_description:
              "need a developer who have an experience in making beautiful layout and ui's and convert figma into react app and intigrate api's as well",
            job_is_remote: true,
            job_posted_at_timestamp: 1688671125,
            job_posted_at_datetime_utc: "2023-07-06T19:18:45.000Z",
            job_city: null,
            job_state: null,
            job_country: "US",
            job_latitude: 37.09024,
            job_longitude: -95.71289,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=czqqS8z6oJ8AAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: [
              "React",
              "JavaScript",
              "Web Development",
              "Redux",
            ],
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
            job_naics_code: "541511",
            job_naics_name: "Custom Computer Programming Services",
          },
          {
            employer_name: "Mindpal",
            employer_logo: null,
            employer_website: null,
            employer_company_type: null,
            job_publisher: "Talent.com",
            job_id: "5bcwhG7mNk8AAAAAAAAAAA==",
            job_employment_type: "FULLTIME",
            job_title: "React developer",
            job_apply_link: "https://www.talent.com/view?id=8f4ee1971702",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.4864,
            job_description:
              "• We are looking for React Developers with experience ranging from junior to senior level.\n• Job Description\n• Creating and developing web applications using React and other front-end tools\n• Working with designers to translate graphical designs into visually appealing and intuitive user interfaces\n• Ensuring application performance and scalability through code optimization and problem-solving related to performance\n• Collaborating with the back-end team to integrate the front-end application with systems and databases\n• Testing and debugging applications to ensure reliability\n• Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications\n• Collaborating with the project team and management to understand business requirements and adjust work to company goals\n• Requirements\n• Minimum 2 years of experience working with React\n• Very good programming skills in JavaScript and TypeScript\n• Knowledge of software architecture, design patterns, and software development according to best practices\n• Additional advantage will be knowledge of other technologies\n• We Offer\n• B2B contract type\n• Full-time employment\n• Remote and flexible working hours\n\nRequirements\n\nResponsibilities\n\nBenefits\n\nLast updated : 2023-07-06",
            job_is_remote: false,
            job_posted_at_timestamp: 1688601600,
            job_posted_at_datetime_utc: "2023-07-06T00:00:00.000Z",
            job_city: "Kansas City",
            job_state: "MO",
            job_country: "US",
            job_latitude: 39.099728,
            job_longitude: -94.57857,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=5bcwhG7mNk8AAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: "2023-10-05T00:00:00.000Z",
            job_offer_expiration_timestamp: 1696464000,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: null,
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "Minimum 2 years of experience working with React",
                "Very good programming skills in JavaScript and TypeScript",
                "Knowledge of software architecture, design patterns, and software development according to best practices",
              ],
              Responsibilities: [
                "Creating and developing web applications using React and other front-end tools",
                "Working with designers to translate graphical designs into visually appealing and intuitive user interfaces",
                "Ensuring application performance and scalability through code optimization and problem-solving related to performance",
                "Collaborating with the back-end team to integrate the front-end application with systems and databases",
                "Testing and debugging applications to ensure reliability",
                "Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications",
                "Collaborating with the project team and management to understand business requirements and adjust work to company goals",
              ],
              Benefits: ["Remote and flexible working hours"],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
            job_occupational_categories: ["15-1252.00"],
          },
          {
            employer_name: "Curbio",
            employer_logo: null,
            employer_website: "http://curbio.com",
            employer_company_type: null,
            job_publisher: "Jobvite",
            job_id: "QwuiV6NotOkAAAAAAAAAAA==",
            job_employment_type: "FULLTIME",
            job_title: "React Developer",
            job_apply_link: "https://jobs.jobvite.com/curbio/job/o9kynfw8",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.8153,
            job_description:
              "Looking to join an innovative and high growth company run by a recognized and successful team of co-founders and executives? Well, it’s an exciting time to join Curbio, a Real Estate Tech company founded in 2017 to transform the multi-billion dollar home improvement and residential real estate market. We help real estate agents and their clients get listings ready for market with smart home improvements and a fix now, pay later model. We are using technology to completely re-invent the archaic home improvement experience and make it work for real estate.\n\nCurbio fosters a creative and supportive work environment that encourages our staff to reach and surpass their full potential. We believe that unity of goals and diversity of people is a powerful combination. We believe that personal responsibility almost always outperforms corporate policies. Our team is focused, driven and inventive.\n\nCurbio has been recognized for exemplary leadership and company culture many times over. In 2022, Curbio made both Inc.’s Top 5000 fastest growing companies in America as well as Deloitte’s Technology Fast 500. We are certified as a Great Place to Work® and our CEO, Rick Rudman, was named a 2021 & 2022 Best CEO by Comparably, where we also received distinctions for Happiest Employees and Best Compensation. Curbio has also been recognized for its success as a tech-powered home improvement solution, receiving nods in the Qualified Remodeler Top 500 list, PropTech Breakthrough awards, Best in Biz awards and NTVC Tech 100 awards, to name a few.\n\nWe won’t bore you with our amazing benefits (they are, we got an award on those too). But if you want to work with an experienced management team that wants to create a great workplace environment, present new opportunities and challenges, provide a clear path for career growth, and work in a collaborative environment with dedicated people - this is the place for you.\n\nJoin Curbio today and help us make real estate move!\n\nAt Curbio you will:\n• Serve as a frontend software developer specializing primarily in React Native, but with React web experience as well.\n• Report directly to the CTO.\n• Communicate – understand when it’s a technical decision vs. a product decision and socialize uncertainties.\n• Pay attention to detail and refactor as you go.\n• Meet with the development team to discuss user interface ideas and applications.\n• Review application requirements and interface designs.\n• Refine the CI/CD pipeline and Cloud Ops processes.\n\nWhat we’re looking for:\n• 5+ years of experience working with React and React Native.\n• Experience working in .Net Framework or .Net Core is a plus.\n• Front End: React & Material Design.\n• Back End: C# .Net Core, SQL Server.\n• Infrastructure: Azure & Azure Functions.\n• A firm commitment to quality code.\n• Experience working as a developer in an agile process with a regular sprint schedule, user stories prioritized from a backlog and sprint reviews, preferred.\n• Native development experience in Swift or Objective-C for iOS, or Java for Android, a plus.\n\nCurbio is proud to be an Equal Opportunity Employer. As such, we are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity, Veteran status or any other characteristic protected under federal, state, or applicable local law",
            job_is_remote: false,
            job_posted_at_timestamp: 1686182400,
            job_posted_at_datetime_utc: "2023-06-08T00:00:00.000Z",
            job_city: null,
            job_state: null,
            job_country: "US",
            job_latitude: 37.09024,
            job_longitude: -95.71289,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=QwuiV6NotOkAAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: 60,
              experience_mentioned: true,
              experience_preferred: true,
            },
            job_required_skills: null,
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "5+ years of experience working with React and React Native",
                "Front End: React & Material Design",
                "Back End: C# .Net Core, SQL Server",
                "Infrastructure: Azure & Azure Functions",
                "A firm commitment to quality code",
              ],
              Responsibilities: [
                "Report directly to the CTO",
                "Communicate – understand when it’s a technical decision vs. a product decision and socialize uncertainties",
                "Pay attention to detail and refactor as you go",
                "Meet with the development team to discuss user interface ideas and applications",
                "Review application requirements and interface designs",
                "Refine the CI/CD pipeline and Cloud Ops processes",
              ],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
          },
          {
            employer_name: "Upwork",
            employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
            employer_website: "http://www.elance.com",
            employer_company_type: "Computer Services",
            job_publisher: "Upwork",
            job_id: "0hzAQaHARLQAAAAAAAAAAA==",
            job_employment_type: "CONTRACTOR",
            job_title: "Full Stack React Developer",
            job_apply_link:
              "https://www.upwork.com/freelance-jobs/apply/Full-Stack-React-Developer_~019decc551ed8b99fb/",
            job_apply_is_direct: true,
            job_apply_quality_score: 0.681,
            job_description:
              "We are seeking a skilled Full Stack React Developer to join our team and help create a cutting-edge web application. The ideal candidate must have strong experience in front-end and back-end development using React and associated technologies. The project is very simple and piece of cake for developer. I am also developer but dont have enough time to work on that. We will use react js along its MUI library to make good design\n\n- 1 or 2 Responsive Webpage(Well SEO Optimized i,e use some good tags title stuff etc) - Major Page\n\n- Contact/FAQ Page (Minor)\n\nthat's all so lets join me i have alot of projects in future. Looking forward to hear from you and discuss in details with you. Thanks",
            job_is_remote: true,
            job_posted_at_timestamp: 1688671915,
            job_posted_at_datetime_utc: "2023-07-06T19:31:55.000Z",
            job_city: null,
            job_state: null,
            job_country: "US",
            job_latitude: 37.09024,
            job_longitude: -95.71289,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=0hzAQaHARLQAAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: [
              "Responsive Design",
              "React",
              "JavaScript",
              "Node.js",
              "CSS",
              "Web Application",
              "HTML",
              "API",
              "HTML5",
            ],
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "The ideal candidate must have strong experience in front-end and back-end development using React and associated technologies",
                "The project is very simple and piece of cake for developer",
                "1 or 2 Responsive Webpage(Well SEO Optimized i,e use some good tags title stuff etc) - Major Page",
              ],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113300",
            job_onet_job_zone: "4",
            job_naics_code: "541511",
            job_naics_name: "Custom Computer Programming Services",
          },
          {
            employer_name: "Upwork",
            employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
            employer_website: "http://www.elance.com",
            employer_company_type: "Computer Services",
            job_publisher: "Upwork",
            job_id: "3blDJ50PALsAAAAAAAAAAA==",
            job_employment_type: "CONTRACTOR",
            job_title: "React Developer - Contract to hire",
            job_apply_link:
              "https://www.upwork.com/en-gb/freelance-jobs/apply/React-Developer_~01b660db0449d5aa3d/",
            job_apply_is_direct: true,
            job_apply_quality_score: 0.681,
            job_description:
              "We are looking for a React Developer that has extensive experience connecting react components into Node.js APIs. Front end team has already built the react components and backend team as built APIs, need help with connection.\n\nCreating a custom in-house CRM/ATS with about 6 different profile types.",
            job_is_remote: true,
            job_posted_at_timestamp: 1688422106,
            job_posted_at_datetime_utc: "2023-07-03T22:08:26.000Z",
            job_city: null,
            job_state: null,
            job_country: "US",
            job_latitude: 37.09024,
            job_longitude: -95.71289,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=3blDJ50PALsAAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: [
              "API Integration",
              "PostgreSQL",
              "NGINX",
              "React",
              "JavaScript",
              "Node.js",
              "TypeScript",
            ],
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: 20,
            job_max_salary: 50,
            job_salary_currency: "USD",
            job_salary_period: "HOUR",
            job_highlights: {},
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
            job_naics_code: "541511",
            job_naics_name: "Custom Computer Programming Services",
          },
          {
            employer_name: "Upwork",
            employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
            employer_website: "http://www.elance.com",
            employer_company_type: "Computer Services",
            job_publisher: "Upwork",
            job_id: "HT7oJ0_DVSUAAAAAAAAAAA==",
            job_employment_type: "CONTRACTOR",
            job_title: "Full Stack React Developer - Contract to Hire",
            job_apply_link:
              "https://www.upwork.com/freelance-jobs/apply/Full-Stack-React-Developer_~01a97c273faaa6b89d/",
            job_apply_is_direct: true,
            job_apply_quality_score: 0.681,
            job_description:
              "We are hiring for a Senior Full Stack Engineer!\n\nAs a Senior Full Stack Engineer on the team, you will possess the skills and confidence to undertake the challenges of working in a fast-paced start-up environment, frequently be taken out of your comfort zone, and relish getting your hands dirty working with and building the next generation of our product platform.\n\nIn this role you will:\n\nWork in a lean and agile development process .\n\nBe committed to product excellence to ensure the smoothest user experience.\n\nBe committed to code quality to ensure efficient development.\n\nHelp define the architecture and technical strategy that guide the engineering team.\n\nConsistently take steps to support the growth and success of your fellow engineers.\n\nAbout You\n\nSelf-motivated individual who takes ownership\n\nCustomer obsessed and quality champion\n\nResults-oriented\n\nHands-on and team-oriented\n\nDesire to work on a product that really matters to its users, that's absolutely central to their success\n\nAbility to adjust, plan and react as needed\n\nProven and demonstrable track record of success with web/mobile consumer-facing development projects.\n\nAbility to accurately estimate software tasks and work to schedule.\n\nGood judgment particularly in high-pressure times\n\nTechnical Skills:\n\nNodejs\n\nNestjs or some other flavor of Nodejs web app framework\n\nModern Javascript, TypeScript and React\n\nBuilding RESTful API’s\n\nSQL and NoSQL (you must understand a database beyond an ORM)\n\nCI/CD, Git, Linters, Agile .. all the basics of day to day software development\n\nExperience building microservices\n\nAzure Cloud\n\nTwilio modules",
            job_is_remote: true,
            job_posted_at_timestamp: 1688725134,
            job_posted_at_datetime_utc: "2023-07-07T10:18:54.000Z",
            job_city: null,
            job_state: null,
            job_country: "US",
            job_latitude: 37.09024,
            job_longitude: -95.71289,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=HT7oJ0_DVSUAAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: ["React", "Node.js", "JavaScript"],
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: false,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: 17,
            job_max_salary: 20,
            job_salary_currency: "USD",
            job_salary_period: "HOUR",
            job_highlights: {
              Qualifications: [
                "Self-motivated individual who takes ownership",
                "Customer obsessed and quality champion",
                "Results-oriented",
                "Desire to work on a product that really matters to its users, that's absolutely central to their success",
                "Ability to adjust, plan and react as needed",
                "Proven and demonstrable track record of success with web/mobile consumer-facing development projects",
                "Ability to accurately estimate software tasks and work to schedule",
                "Good judgment particularly in high-pressure times",
                "Nestjs or some other flavor of Nodejs web app framework",
                "Modern Javascript, TypeScript and React",
                "SQL and NoSQL (you must understand a database beyond an ORM)",
                "CI/CD, Git, Linters, Agile .. all the basics of day to day software development",
                "Experience building microservices",
              ],
              Responsibilities: [
                "As a Senior Full Stack Engineer on the team, you will possess the skills and confidence to undertake the challenges of working in a fast-paced start-up environment, frequently be taken out of your comfort zone, and relish getting your hands dirty working with and building the next generation of our product platform",
                "Work in a lean and agile development process ",
                "Be committed to product excellence to ensure the smoothest user experience",
                "Be committed to code quality to ensure efficient development",
                "Help define the architecture and technical strategy that guide the engineering team",
                "Consistently take steps to support the growth and success of your fellow engineers",
              ],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
            job_naics_code: "541511",
            job_naics_name: "Custom Computer Programming Services",
          },
        ]);
      } else if (endpoint == "job-details") {
        setData([
          {
            employer_name: "Mindpal",
            employer_logo:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKdbXDdBF2_8ZRV4qszl-0nJx1pneJLHoI9D9d&s=0",
            employer_website: null,
            employer_company_type: null,
            job_publisher: "LinkedIn",
            job_id: "EV02pCkgcY4AAAAAAAAAAA==",
            job_employment_type: "FULLTIME",
            job_title: "React Developer",
            job_apply_link:
              "https://www.linkedin.com/jobs/view/react-developer-at-mindpal-3656112725",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6065,
            job_description:
              "• We are looking for React Developers with experience ranging from junior to senior level.\n• Job Description\n• Creating and developing web applications using React and other front-end tools\n• Working with designers to translate graphical designs into visually appealing and intuitive user interfaces\n• Ensuring application performance and scalability through code optimization and problem-solving related to performance\n• Collaborating with the back-end team to integrate the front-end application with systems and databases\n• Testing and debugging applications to ensure reliability\n• Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications\n• Collaborating with the project team and management to understand business requirements and adjust work to company goals\n• Requirements\n• Minimum 2 years of experience working with React\n• Very good programming skills in JavaScript and TypeScript\n• Knowledge of software architecture, design patterns, and software development according to best practices\n• Communicative knowledge of English language\n• Additional advantage will be knowledge of other technologies\n• We Offer\n• B2B contract type\n• Full-time employment\n• Remote and flexible working hours\n\nRequirements\n\nResponsibilities",
            job_is_remote: false,
            job_posted_at_timestamp: 1688564550,
            job_posted_at_datetime_utc: "2023-07-05T13:42:30.000Z",
            job_city: "Wichita",
            job_state: "KS",
            job_country: "US",
            job_latitude: 37.687176,
            job_longitude: -97.330055,
            job_benefits: null,
            job_google_link:
              "https://www.google.com/search?gl=us&hl=en&q=EV02pCkgcY4AAAAAAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=EV02pCkgcY4AAAAAAAAAAA%3D%3D&htidocid=EV02pCkgcY4AAAAAAAAAAA%3D%3D",
            job_offer_expiration_datetime_utc: "2023-08-04T13:42:30.000Z",
            job_offer_expiration_timestamp: 1691156550,
            job_required_experience: {
              no_experience_required: false,
              required_experience_in_months: null,
              experience_mentioned: true,
              experience_preferred: false,
            },
            job_required_skills: null,
            job_required_education: {
              postgraduate_degree: false,
              professional_certification: false,
              high_school: false,
              associates_degree: false,
              bachelors_degree: true,
              degree_mentioned: false,
              degree_preferred: false,
              professional_certification_mentioned: false,
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {
              Qualifications: [
                "Minimum 2 years of experience working with React",
                "Very good programming skills in JavaScript and TypeScript",
                "Knowledge of software architecture, design patterns, and software development according to best practices",
                "Communicative knowledge of English language",
              ],
              Responsibilities: [
                "Creating and developing web applications using React and other front-end tools",
                "Working with designers to translate graphical designs into visually appealing and intuitive user interfaces",
                "Ensuring application performance and scalability through code optimization and problem-solving related to performance",
                "Collaborating with the back-end team to integrate the front-end application with systems and databases",
                "Testing and debugging applications to ensure reliability",
                "Keeping up with the latest trends and tools in front-end development and improving skills to continuously enhance the quality of created applications",
                "Collaborating with the project team and management to understand business requirements and adjust work to company goals",
              ],
              Benefits: ["Remote and flexible working hours"],
            },
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "15113400",
            job_onet_job_zone: "3",
            estimated_salaries: [],
            apply_options: [
              {
                publisher: "Talent.com",
                apply_link:
                  "https://www.talent.com/view?id=6de119ddf867&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                is_direct: false,
              },
            ],
            employer_reviews: [],
          },
        ]);
      }
      setIsLoading(false);
    } catch (error) {
      setError(error);
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const refetch = () => {
    setIsLoading(true);
    fetchData();
  };

  return { data, isLoading, error, refetch };
};

export default useFetch;
